# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /
    controller:  App\Controller\MainController::index
app_index:
    path: /main
    controller:  App\Controller\MainController::index
app_login:
    path: /faculty/login
    controller: App\Controller\SecurityController::login
app_valuepairs:
    path: /valuepairs/{table}/{valuefield}/{displayfield}/{orderfield}
    controller:  App\Controller\MainController::valuepairs
logout_message:
    path: /logout_message
    controller: App\Controller\SecurityController::logoutMessage
faculty_faculty:
    path: /faculty/faculty
    controller: App\Controller\FacultyController::index
faculty_faculty_list:
    path: /faculty/faculty/list/{startIndex}/{pageSize}/{sorting}
    controller: App\Controller\FacultyController::list
faculty_faculty_create:
    path: /faculty/faculty/create
    controller: App\Controller\FacultyController::create
faculty_faculty_update:
    path: /faculty/faculty/update
    controller: App\Controller\FacultyController::update
faculty_student:
    path: /faculty/student
    controller: App\Controller\StudentController::index