# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: en
    app.notifications.email_sender: anonymous@example.com
    library_directory: '%kernel.project_dir%/public/build/library/'
    # These parameters define the academic year, they should be adjusted every year
    # Semesters
    first_semester_year: 2023
    second_semester_year: 2024
    third_semester_year: 2024
    
    current_semester_year: 2024
    
    first_semester_begin_date: '2023-09-01'
    first_semester_end_date: '2024-01-05'
    first_semester_final_end_date: '2024-02-02'
    first_semester_fourth_year_end_date: '2024-01-05'
    
    second_semester_begin_date: '2024-02-02'
    second_semester_end_date: '2024-06-08'
    second_semester_final_end_date: '2024-06-29'
    second_semester_fourth_year_end_date: '2024-05-25'
    
    # NOTE!!! Third semester info should be the same as second semester info. There is no real third semester for now
    third_semester_begin_date: '2024-02-02'
    third_semester_end_date: '2024-06-08'
    third_semester_final_end_date: '2024-06-29'
    third_semester_fourth_year_end_date: '2024-05-25'
    
    # Trimesters
    first_trimester_year: 2023
    second_trimester_year: 2023
    third_trimester_year: 2024
    
    first_trimester_begin_date: '2023-09-01'
    first_trimester_end_date: '2023-11-24'
    first_trimester_final_end_date: '2023-12-01'
    
    second_trimester_begin_date: '2023-12-08'
    second_trimester_end_date: '2024-03-02'
    second_trimester_final_end_date: '2024-03-10'
    
    third_trimester_begin_date: '2024-03-11'
    third_trimester_end_date: '2024-06-07'
    third_trimester_final_end_date: '2024-06-15'
    
    current_trimester_year: 2024
    #current_trimester_begin_date: '2020-09-01'
    #current_trimester_end_date: '2020-11-24'
    #current_trimester_final_end_date: '2020-12-01'
    # Current semester and trimester
    current_semester: 2
    current_trimester: 3
    # Special system ids
    lld_system_id: 66
    
    # defines public build path
    root_path: 'c:/campus/www/campus3'
    public_build_path: 'c:/campus/www/campus3/public/build'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $emailSender: '%app.notifications.email_sender%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Hr\Controller\:
        resource: '../src/Hr/Controller'
        tags: ['controller.service_arguments']
    App\Registrar\Controller\:
        resource: '../src/Registrar/Controller'
        tags: ['controller.service_arguments']
    App\Kiosk\Controller\:
        resource: '../src/Kiosk/Controller'
        tags: ['controller.service_arguments']
    App\Library\Controller\:
        resource: '../src/Library/Controller'
        tags: ['controller.service_arguments']
    # when the service definition only contains arguments, you can omit the
    # 'arguments' key and define the arguments just below the service class
    App\EventSubscriber\CommentNotificationSubscriber:
        $sender: '%app.notifications.email_sender%'

    # needed to activate the filters provided by Twig Intl Extension
    Twig\Extra\Intl\IntlExtension: null